### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by solarite1797** [addi00000/empyrean#100]
**Describe the bug**
i keep getting "The system could not find the file specified."

**To Reproduce**
build on windows 11 22h2

**Expected behavior**
the grabber should be built

**Screenshots**
![image](https://user-images.githubusercontent.com/118111762/208075219-60c037eb-76cb-47d0-8be7-e681d1ae5e63.png)

**Additional context**
no clue

**Comment by solarite1797** [comment]
help

**Comment by Wizz1337** [comment]
create build folder if not already one in this folder create src folder and put the 'main.py' in this repo src folder (empyrean/src/main.py)

**Comment by DirtMonkey** [comment]
I have the same issue and I already have what you said to do
