### ISSUE TITLE
[BUG] HWID failing

### ISSUE THREAD

**Issue by lolcakes69** [addi00000/empyrean#101]
**Describe the bug**

**To Reproduce**
1. use exe
2. it will send the 1st 2 messages (vault.zip and the message with token)
3. discord restarts for desktop image
`Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "main.py", line 25, in main
  File "components\antidebug.py", line 13, in init
  File "components\antidebug.py", line 35, in checks
  File "components\antidebug.py", line 58, in get_system
  File "subprocess.py", line 421, in check_output
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command 'C:\Windows\System32\wbem\WMIC.exe csproduct get uuid' returned non-zero exit status 3221225477.`

**Expected behavior**
expecting 3rd message with system info and desktop screenshot to come through, but it doesn't

**Screenshots**

**Additional context**
this is on a fresh w10 system for testing, not sure what dependencies the computer must have for this to run

**Comment by Wizz1337** [comment]
a error occured while getting hwid
@addi00000 must add try except for here

**Comment by addi00000** [comment]
Yeah some people dont seem to have WMIC in the correctly. I will probably just add a check for if the user has the path and skip if not instead

**Comment by addi00000** [comment]
Actually i may just add try catch since I'm lazy and dont know if this error actually specifies that there is no wmic path
