### ISSUE TITLE
[BUG] File not found

### ISSUE THREAD

**Issue by adi0sryan** [addi00000/empyrean#104]
**Describe the bug**
The bug is that when I run build.bat, it crashes at the end and says the system cannot find the file specified
**To Reproduce**
1. Go to 'empyrean'
2. Click on 'build.bat'
3. See error

**Expected behavior**
I expected that a dist folder was made containg the logger

**Screenshots**
[Photo 1](https://drive.google.com/file/d/1ovV7OcIT6tuASE-Q2eH4le5DVSLh4QQd/view?usp=share_link)

**Comment by Your-Bestie-2** [comment]
dont delete the file first maybe
