### ISSUE TITLE
the discord link expired

### ISSUE THREAD

**Issue by ScarzWW** [addi00000/empyrean#110]
**Describe the bug**

**To Reproduce**
1. new discord link

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Kingplayer786** [comment]
You got the dc link yet?

**Comment by RushTwo** [comment]
Can u give me the new Discords Link please ?

**Comment by Your-Bestie-Was-Banned** [comment]
[yall fr?
ong](https://discord.gg/5SsY9pfq)
