### ISSUE TITLE
[BUG] not running

### ISSUE THREAD

**Issue by Sutriv** [addi00000/empyrean#118]
**Describe the bug**
IDK why maybe because me a friend is doing it on Linux but we are getting 5/6 errors and we just cant run the build.

**To Reproduce**
1. open terminal
2. go to the files folder
3. type ./build.bat or type bash build.sh (we tried to modify the code and the name to sh but it didn't work)
4. See the error

**Expected behavior**
we get a working program 

**Additional context**
it may be because we are using Linux and not windows but from the code, i think it shouldn't matters 
![23b54e584909823c27843199bdeac23a](https://user-images.githubusercontent.com/88074226/210608481-36d18603-920f-4d12-b25f-c3bdeb4c6f4f.png)

**Comment by Your-Bestie-Was-Banned** [comment]
OMFG.

**Comment by Your-Bestie-Was-Banned** [comment]
maybe cuz you cant run windows bat files on kali, the fact that you are using kali and dont know this...

**Comment by Sutriv** [comment]
we tried it on windows and had similar results

**Comment by Your-Bestie-Was-Banned** [comment]
why do you even have a kali machine? also then post the windows one not the damn kali one

**Comment by Sutriv** [comment]
not me but my friend and he is kinda stupid so that might be the reason and he have kali cuz he uses it for school so he tried running it on it.

**Comment by addi00000** [comment]
This code is incompatible with *NIX os’s. If you have an issue running this on windows 10/11 then you can open an issue specifically about that but otherwise this issue is invalid.

**Comment by Your-Bestie-Was-Banned** [comment]
also how you gonna rename the file and think thats gonna change it

**Comment by Your-Bestie-Was-Banned** [comment]
i wish i could delete you 😭

**Comment by Your-Bestie-Was-Banned** [comment]
he tried everything besides running linix commands on linux
