### ISSUE TITLE
how do I target another user?

### ISSUE THREAD

**Issue by alpgithubx** [addi00000/empyrean#121]
when I run main.exe, it immediately just sends my info to the server. how do I change the username that's being targeted?

**Comment by Your-Bestie-Was-Banned** [comment]
OMG YES PLZ

**Comment by Your-Bestie-Was-Banned** [comment]
ARE YOU TROLLING OR FR?

**Comment by alpgithubx** [comment]
for real?

**Comment by alpgithubx** [comment]
i'm fucked, am I not?
what's supposed to happen?

**Comment by alpgithubx** [comment]
lmao
..?

**Comment by ai24i** [comment]
how to target a user?
do i just send them the main.pi?

**Comment by nagogy** [comment]
use your brain

**Comment by ai24i** [comment]
wdym? TELL ME

**Comment by apekilla890** [comment]
Yeah what exactly do you send to the user and what do they need installed or need to do in order for it to work?

**Comment by addi00000** [comment]
> Yeah what exactly do you send to the user and what do they need installed or need to do in order for it to work?

once the exe is compiled you just send that file

**Comment by addi00000** [comment]
> when I run main.exe, it immediately just sends my info to the server. how do I change the username that's being targeted?

there is no targetted username
this will work with anyone as long as the run the file on windows

**Comment by apekilla890** [comment]
> 

How would this work if the user is on mobile. Does it even work?

**Comment by alpgithubx** [comment]
im facepalming rn

**Comment by alpgithubx** [comment]
wait

**Comment by alpgithubx** [comment]
the github to discord server sync is soo good 🤤

**Comment by alpgithubx** [comment]
anyways im deleting this issue
