### ISSUE TITLE
[BUG] Not sure if this is an actual bug, or if I'm just SLOW. Based on past experience, it really could go either way.

### ISSUE THREAD

**Issue by CarKeat** [addi00000/empyrean#122]
**Describe the bug**
Build.bat never crashes,but asks for a webhook before proceeding. I see nothing on in the files that show a webhook, so I'm not allowed to continue. Also, built.exe does not seem to exist. I looked everywhere. 

**To Reproduce**
1. Go to empyrean-main
2. Click on 'build.bat"
3. Let run
4. Stuck at "Enter your webhook URL"
![yo](https://user-images.githubusercontent.com/122135288/211781284-43fc408a-0841-4e10-a221-3ad4b12f8040.png)

**Expected behavior**
Stuck at asking for your URL webhook

**Screenshots**

**Additional context**
Again, if this is not a Bug and I just didn't see what was in front of me the whole time, I apologize.

**Comment by nagogy** [comment]
you have to put your discord webhook in
https://hookdeck.com/webhooks/platforms/how-to-get-started-with-discord-webhooks

btw right click to paste in cmd

**Comment by CarKeat** [comment]
Awesome, thank you! And thanks for the tip!

**Comment by nagogy** [comment]
np
