### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by flameryy** [addi00000/empyrean#123]
when I give the command "./build.bat" I get the message that the permission was denied. does anyone know how to resolve?

**Comment by nagogy** [comment]
try running as admin

**Comment by Your-Bestie-Was-Banned** [comment]
??!?!

**Comment by flameryy** [comment]
what?

**Comment by Your-Bestie-Was-Banned** [comment]
wdym by that

**Comment by flameryy** [comment]
I gave the command "cd empyrean", then entered "git clone https://github.com/addi00000/empyrean.git". Then I put "./build.batbat" and it says that the file cannot be found. what do i do?

**Comment by flameryy** [comment]
I'm a little new to this, I still don't know how to run as administrator
