### ISSUE TITLE
[BUG] yo mf ur permission is denying and shi on python 3.11

### ISSUE THREAD

**Issue by OoniUni** [addi00000/empyrean#128]
**PermissionError: [WinError 5] Access is denied:**
Shits showing that error when using python 3.11 but works on 3.10 idk.

**To Reproduce**
1. Just install 3.11.0
2. Try to run the builder
3. after putting the webhook and putting y/n
4. the error will show up

**Expected behavior**
The program shoulda started building the EXE.

Might be that this shit dont work on py 3.11 but idk

**Comment by KDot227** [comment]
> **PermissionError: [WinError 5] Access is denied:** Shits showing that error when using python 3.11 but works on 3.10 idk.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Just install 3.11.0
> 2. Try to run the builder
> 3. after putting the webhook and putting y/n
> 4. the error will show up
> 
> **Expected behavior** The program shoulda started building the EXE.
> 
> Might be that this shit dont work on py 3.11 but idk

Nothing works on 3.11 yet

**Comment by KDot227** [comment]
Also @OoniUni smd

**Comment by nagogy** [comment]
frrrr

**Comment by KDot227** [comment]
And hop on apex

**Comment by Bang-Bang-Ban** [comment]
dont use 3.11?!?!?!? smfh

**Comment by KDot227** [comment]
> dont use 3.11?!?!?!? smfh

3.11 haram. Mashallah🙏🙏🙏

**Comment by nagogy** [comment]
tf?

**Comment by Bang-Bang-Ban** [comment]
kdot sand nigger confirmed?

**Comment by Bang-Bang-Ban** [comment]
Kdot sand dude confirmed

**Comment by Bang-Bang-Ban** [comment]
> tf?

shouldnt u be in bed?

**Comment by OoniUni** [comment]
> > **PermissionError: [WinError 5] Access is denied:** Shits showing that error when using python 3.11 but works on 3.10 idk.
> > 
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Just install 3.11.0
> > 2. Try to run the builder
> > 3. after putting the webhook and putting y/n
> > 4. the error will show up
> > 
> > **Expected behavior** The program shoulda started building the EXE.
> > 
> > Might be that this shit dont work on py 3.11 but idk
> 
> Nothing works on 3.11 yet

alr thank you zaddy uwu

**Comment by nagogy** [comment]
> > tf?
> 
> shouldnt u be in bed?

uh smd

**Comment by nagogy** [comment]
> > tf?
> 
> shouldnt u be in bed?

racist

**Comment by KDot227** [comment]
> > > **PermissionError: [WinError 5] Access is denied:** Shits showing that error when using python 3.11 but works on 3.10 idk.
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Just install 3.11.0
> > > 2. Try to run the builder
> > > 3. after putting the webhook and putting y/n
> > > 4. the error will show up
> > > 
> > > **Expected behavior** The program shoulda started building the EXE.
> > > Might be that this shit dont work on py 3.11 but idk
> > 
> > 
> > Nothing works on 3.11 yet
> 
> alr thank you zaddy uwu

Fasho

**Comment by addi00000** [comment]
#129
