### ISSUE TITLE
[FEAT.]

### ISSUE THREAD

**Issue by apekilla890** [addi00000/empyrean#130]
Is there anyway to make it so if the user trys to download the file that it doesn't pop up as a threat? Obviously if they have strict virus and threat protection on it'll let them know but is there anything to bypass it and make it things it's a safe and normal file? Also how would this work on mobile users?

**Comment by nagogy** [comment]
skid!

**Comment by chiron853** [comment]
> skid!

how to be retarded tutorial part 1

**Comment by KDot227** [comment]
> > skid!
> 
> how to be retarded tutorial part 1

Nah
