### ISSUE TITLE
Google Chrome detects it as a virus, does not allow downloading the file. [BUG]

### ISSUE THREAD

**Issue by ilhan77777** [addi00000/empyrean#135]
Google Chrome detects it as a virus, does not allow downloading the file. [BUG]

**Comment by addi00000** [comment]
Use a zip file and maybe a password

**Comment by ilhan77777** [comment]
The victim will not run a exe if it is in the zip file.
I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.

**Comment by Bang-Bang-Ban** [comment]
@ilhan77777 i have tool cumming soon that drops empyrean fud, but other than that just wait

**Comment by ilhan77777** [comment]
[Bang-Bang-Ban](https://github.com/Bang-Bang-Ban) It would be fine, I'm waiting.

**Comment by KDot227** [comment]
> The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.

the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.

**Comment by KDot227** [comment]
in the meantime try using a file sharing site like gofile or anonfiles

**Comment by ilhan77777** [comment]
> > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> 
> the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.

google suspicious file warning is happening with almost every zip file and there is still download option.
But this payload is directly marked as virus and download becomes impossible. 

it also started to detected in windows defender today. totally useless right now.

**Comment by ilhan77777** [comment]
> 

I am not a programmer.

**Comment by ilhan77777** [comment]
> 
@nagogy
I am not a programmer. If you tell me how to do this, I can try.

**Comment by nagogy** [comment]
learn how to do it, dont complain to someone else that you cant hack kids

**Comment by KDot227** [comment]
> > 
> 
> @nagogy I am not a programmer. If you tell me how to do this, I can try.

This has nothing to do with programming.

**Comment by Bang-Bang-Ban** [comment]
> > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> 
> the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.

@KDot227 u mostly just have to pay for a [code signature](https://en.wikipedia.org/wiki/Code_signing)

**Comment by KDot227** [comment]
> > > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> > 
> > 
> > the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.
> 
> @KDot227 u mostly just have to pay for a [code signature](https://en.wikipedia.org/wiki/Code_signing)

Yes, but I don't think anybody is going to give up the 900$ for one 💀

**Comment by KDot227** [comment]
> > > > > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> > > > 
> > > > 
> > > > the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.
> > > 
> > > 
> > > @KDot227 u mostly just have to pay for a [code signature](https://en.wikipedia.org/wiki/Code_signing)
> > 
> > 
> > Yes, but I don't think anybody is going to give up the 900$ for one 💀
> 
> frrr 😭

has anyone tried using something like signtool or maybe even having a service that just has one signed dropper and uses that?

**Comment by Bang-Bang-Ban** [comment]
> has anyone tried using something like signtool or maybe even having a service that just has one signed dropper and uses that?

thats my plan with code zero ngl, if everyone pitches in with the "paid" plan then it will be only like $10 a month per person

**Comment by KDot227** [comment]
> > has anyone tried using something like signtool or maybe even having a service that just has one signed dropper and uses that?
> 
> thats my plan with code zero ngl, if everyone pitches in with the "paid" plan then it will be only like $10 a month per person

I ain't even know u in code zero

**Comment by Bang-Bang-Ban** [comment]
?!

**Comment by KDot227** [comment]
> ?!

What's your user

**Comment by KDot227** [comment]
> your bestie 💀 

Bruh smd + kys

**Comment by Bang-Bang-Ban** [comment]
sounds like fun roleplay ngl

**Comment by KDot227** [comment]
> sounds like fun roleplay ngl

![image](https://user-images.githubusercontent.com/110929758/213792954-1202051f-75d1-4007-a40f-e526d0f65246.png)

**Comment by ilyigna** [comment]
> > > > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> > > 
> > > 
> > > the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.
> > 
> > 
> > @KDot227 u mostly just have to pay for a [code signature](https://en.wikipedia.org/wiki/Code_signing)
> 
> Yes, but I don't think anybody is going to give up the 900$ for one 💀

u can get one for 80, also afaik using rust u can make it don't show the google thing (i've made a dropper on rust, never got chrome detects or something)

**Comment by KDot227** [comment]
> > > > > The victim will not run a exe if it is in the zip file. I want it to create sfx archive and run it with pdf file, but it also detect sfx archive as virus.
> > > > 
> > > > 
> > > > the reason that happens is cause it's not downloaded a lot and is suspected to be suspicious. Even a FUD dropper won't fix this issue unless it is being constantly downloaded by multiple sites over a longer period of time.
> > > 
> > > 
> > > @KDot227 u mostly just have to pay for a [code signature](https://en.wikipedia.org/wiki/Code_signing)
> > 
> > 
> > Yes, but I don't think anybody is going to give up the 900$ for one 💀
> 
> u can get one for 80, also afaik using rust u can make it don't show the google thing (i've made a dropper on rust, never got chrome detects or something)

I made a dropper too and with some testing I think your right about that.
