### ISSUE TITLE
got java error code and it didnt let me open discord

### ISSUE THREAD

**Issue by alorissh** [addi00000/empyrean#140]
why did i get error code for my discord and needed to uninstall and install discord again to open discord?

**Comment by ilylunar** [comment]
> why did i get error code for my discord and needed to uninstall and install discord again to open discord?

That's due to an error of the injection:

- Go to **AppData\Local\Discord\app-1.0.9008\modules\discord_desktop_core-1\discord_desktop_core**
- Edit **index.js** with notepad or whatever
- Delete everything and replace with just one line: **module.exports = require('./core.asar');**

**Comment by Wizz1337** [comment]
@addi00000 close
