### ISSUE TITLE
[BUG] virus

### ISSUE THREAD

**Issue by oji6ixx** [addi00000/empyrean#152]
**Describe the bug**
While building it also installs a trojan virus is this normal?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/124367024/216611084-d00c0140-9433-4d2b-9b26-258ccac8e171.png)

**Additional context**

**Comment by DARKNOSY** [comment]
Isn't it just detecting the builded trojan

**Comment by oji6ixx** [comment]
> Isn't it just detecting the builded trojan

trojans arent good, at all

**Comment by DARKNOSY** [comment]
What

**Comment by xX-MoonWalker-Xx** [comment]
dude im losing braincells by just reading these 😂😂😂😂😂

**Comment by Retartek** [comment]
Well acctually I have some screenshots of the owner saying he has a backdoor in the code he stole my friends discord acc when we wanted to try out empyrean and some random Person got the account I was the only Person with a webhook. 5min later he changed pw and everything and we had this conversation 
![Uploading Screenshot_20230424_081005_Discord.jpg…]()

**Comment by Retartek** [comment]
Now my question is does it affect only ppl who executed the main.exe or also the person that built it

**Comment by DARKNOSY** [comment]
Screenshot didn't upload can you upload it on a file hoster or image hoster?
