### ISSUE TITLE
Empyrean is BROKEN

### ISSUE THREAD

**Issue by MrShadowDev** [addi00000/empyrean#153]
**Describe the bug**
![a](https://i.imgur.com/Fy151wv.png)

**Comment by AppelSappie123** [comment]
> **Describe the bug**
> 
> ![a](https://i.imgur.com/Fy151wv.png)

1. Delete python
2. Install python 3.10.8
3. Open cmd and type "pip install -r requirements.txt"
4. Open cmd and type "python main.py"

That's it

**Comment by MrShadowDev** [comment]
Already solved it the same day just forgot to close this issue.
