### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nb52** [addi00000/empyrean#155]
**Describe the bug**
I'm getting this error while trying to build

**To Reproduce**
1. Go to empyrean-main
2. Click on build.bat
3. Enter webhook and config

**Expected behavior**
I expected the builder to create the .exe

**Screenshots**
https://ibb.co/mcX9D0D

**Additional context**

**Comment by AppelSappie123** [comment]
I had the same error. Try to reinstall.

**Comment by sabaasa** [comment]
have the exactt same error, dont know whats wrong

**Comment by AppelSappie123** [comment]
> have the exactt same error, dont know whats wrong

1. Delete python
2. Install python 3.10.8
3. Open cmd and type "pip install -r requirements.txt"
4. Open cmd and type "python main.py"

That's it

**Comment by AppelSappie123** [comment]
> **Describe the bug**
> 
> I'm getting this error while trying to build
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to empyrean-main
> 
> 2. Click on build.bat
> 
> 3. Enter webhook and config
> 
> 4. See error
> 
> 
> 
> **Expected behavior**
> 
> I expected the builder to create the .exe
> 
> 
> 
> **Screenshots**
> 
> https://ibb.co/mcX9D0D
> 
> 
> 
> **Additional context**
> 
> Add any other context about the problem here.
> 
> 

1. Delete python
2. Install python 3.10.8
3. Open cmd and type "pip install -r requirements.txt"
4. Open cmd and type "python main.py"

That's it

**Comment by sabaasa** [comment]
I hate python man why tf do I need to install different versions of python for literally every single .py file I download
