### ISSUE TITLE
Delete Discord injection

### ISSUE THREAD

**Issue by lolgamerslol9812** [addi00000/empyrean#157]
So i tried the discord injection on myself and i dont know how to get rid of it
Please help me

**Comment by NewMicahLangley** [comment]
uninstall discord reinstall it

**Comment by NewMicahLangley** [comment]
☠️

**Comment by MrShadowDev** [comment]
Yes, just reinstall discord its easy!

**Comment by RE-108** [comment]
Uninstalling ok, but where is the injection saved in?

**Comment by Blitzedzz** [comment]
no

**Comment by MrShadowDev** [comment]
> Uninstalling ok, but where is the injection saved in?

Its on the Discord App Data Folder when you uninstall and install it again it gets deleted itself because you deleted the Discord app. Its easy man :)
