### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Akheyy** [addi00000/empyrean#158]
After building of exe file when I check it in dist folder then it shows this folder is empty , In fact I put my all antivirus or firewall disable... agiain it creates that problem I reinstalled 4 times again it shows that problem

**Comment by AppelSappie123** [comment]
I have the same problem.

**Comment by AppelSappie123** [comment]
> After building of exe file when I check it in dist folder then it shows this folder is empty , In fact I put my all antivirus or firewall disable... agiain it creates that problem I reinstalled 4 times again it shows that problem
> 
> 

1. Delete python
2. Install python 3.10.8
3. Open cmd and type "pip install -r requirements.txt"
4. Open cmd and type "python main.py"

That's it
