### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrShadowDev** [addi00000/empyrean#162]
I'm optimizing this repository to make my own stealer. Im asking for permission.

**Comment by MrShadowDev** [comment]
Im making an optimized version of the code.

**Comment by MrShadowDev** [comment]
No no, im not making a carbon copy. I'll optimize the code and add more features. But before i make it i want to ask you.

**Comment by addi00000** [comment]
Once again i don't care and cant do anything about it but you should try to contribute instead of taking my whole codebase and adding a few things and passing it off.

**Comment by MrShadowDev** [comment]
Ok.
