### ISSUE TITLE
i cannot find the exe logger

### ISSUE THREAD

**Issue by jaybarksloolo** [addi00000/empyrean#165]
cant find exe 
![image](https://user-images.githubusercontent.com/121317314/219512244-c40be881-f8ce-4bae-8270-21860d0778d8.png)

**Comment by PeakScripts** [comment]
@jaybarksloolo how did u fix it?

**Comment by jaybarksloolo** [comment]
> @jaybarksloolo how did u fix it?

i forgot sorry
