### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cauazola** [addi00000/empyrean#184]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "components\browsers.py", line 9, in <module>
ImportError: cannot import name 'Embed' from 'discord' (unknown location)

Everytime i open the exe

![Print](https://user-images.githubusercontent.com/126132338/221390173-866fbf1e-0256-4b28-a553-03e20706116d.png)

**Comment by Wizz1337** [comment]
Hi, can you open a command line (CMD) and execute this command : `pip show discord` and then send the result here ?
![image](https://user-images.githubusercontent.com/70026238/221404104-bcc91dec-48b4-4f73-858e-68c2cdedd5aa.png)

**Comment by cauazola** [comment]
Sorry for the delay my friend

![image](https://user-images.githubusercontent.com/126132338/221451384-b3a7fa8c-61bf-42c8-9826-54f9717e3875.png)

**Comment by Wizz1337** [comment]
can you try to do `pip uninstall discord` and then `pip install discord`
