### ISSUE TITLE
[BUG] How To Remove Injection? 

### ISSUE THREAD

**Issue by AaryavS** [addi00000/empyrean#187]
Someone Did This To Me. HOW do I remove it?

**Comment by AdamxzV3** [comment]
Check my github (Discord Disinfector) this is 2 week old code try it just make an .bat file

set folder=empyrean
set fpath=%AppData%\%folder%
if exist "%fpath%" (
    rmdir /s /q "%fpath%"
    echo Folder "%folder%" has been succesfully deleted from "%AppData%".
) else (
    echo Folder "%folder%" have not been found in "%AppData%".
)
pause

**Comment by AdamxzV3** [comment]
or reinstall discord

**Comment by AdamxzV3** [comment]
also if the 'Discord Disinfector' Helped you i would be happy if you will ⭐ the project

**Comment by GoldenAxolotl** [comment]
remove empyrean folder in %appdata% and delete run at startup files at regedit
