### ISSUE TITLE
eror dafuq

### ISSUE THREAD

**Issue by Nice2Basic** [addi00000/empyrean#19]
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_clr required by hook for module C:\Users\user\AppData\Roaming\Python\Python310\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py. Please check whether module __PyInstaller_hooks_0_clr actually exists and whether the hook is compatible with your version of C:\Users\user\AppData\Roaming\Python\Python310\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

**Comment by Smug246** [comment]
do you have the most recent version of python?

**Comment by 6nz** [comment]
> do you have the most recent version of python?

Py version doesnt matter here also he is using 3.10
