### ISSUE TITLE
Not Sending Token

### ISSUE THREAD

**Issue by matrixishim92743** [addi00000/empyrean#203]
Why does it just send the information of the pc but not the token, i did yes to token log on build.bat

**Comment by PeakScripts** [comment]
maybe cus they dont have discord app installed?

**Comment by DarkGamer209788** [comment]
Same thing here. I'm only getting the vault uploaded but no discord token embed is showing up. Tried it on myself as well. I think it might have to do with some new way discord is hiding the token but I'm not so sure
