### ISSUE TITLE
A tutorial on building this

### ISSUE THREAD

**Issue by DarkGamer209788** [addi00000/empyrean#218]
I saw a lot of issues here because people don't know to build this.

1. Download and extract the file by pressing on code and downloading the zip.
2. Double click on the file _installpython.bat_ or _installpython_
3. Double click on the file _build.bat_ or _build_.
4. This will open in command prompt and automatically install necessary files for the grabber to work.
5. Go to discord and create a new channel (or use an existing one) where you want to stolen information to come. Press the settings icon (edit channel) and go to integrations. Then go to Webhooks and create a new webhook. It can have any name, however, you want to copy the webhook url.
6. Back in command prompt, if it asks for your webhook url, make sure you have copied it and right-click to paste. Press enter to continue
7. Anti-debugging - Not sure what this does but you should probably leave it on.
8. Browser stealing  - Steals browser info like logins, cookies and history as well as downloads.
9. Enable discord token stealing - This will steal the token.
10. Enable discord injection - This will inject the file to their discord
11. Enable startup - This will make the logger always run whenever the victim's pc is turned on.
12. Enable system info - This will also log the system info 

After doing this it will build the file that when run, will log the information
You can find the product in the _dist_ folder named _main.exe_ which is sent to the victim, and when run, will log all the information and send it in the channel where you created the webhook.

**Issues**
I don't know why this happens, but for me the token is not being logged, but the system information does come

**Removing the file**
The files are found in your roaming folder. You can access this by pressing **Windows + R** and searching for the folder named _empyrean_ where you will find all the files that are logging the information.

**Comment by KDot227** [comment]
u might have a non english name as ur user and that can cause issues with finding paths. I could also be 100% wrong just try sum else. (reset windows fixes everything)
