### ISSUE TITLE
?

### ISSUE THREAD

**Issue by godless123123123** [addi00000/empyrean#220]
how do you use it on someone else?

**Comment by Nu-Git** [comment]
make an autorun script and plug it into their Windows computer or
Trick them into running it instead of an actual thing, such as renaming it to *NAME*.pdf.bat, since most normal people keep the file extensions hidden, and changing the file icon to a pdf icon

**Comment by Nu-Git** [comment]
use an online converter to convert cookies.txt into cookies.json and import with a browser extension
