### ISSUE TITLE
[FEAT.] integrate the token grabb into another program

### ISSUE THREAD

**Issue by Eloy-coding** [addi00000/empyrean#225]
Hello,
I would like to be able to integrate the token grabb to one of my programs but I don't do python so I don't recognize the main code that grabb the token.

Could you tell me what is this piece of code that allows to grab the token plz ?
I want the grabb to run when the program is executed without us noticing it like the .exe file generated after using "build.bat" in empyrean-main.

**Comment by KDot227** [comment]
90% sure there is a function called Tokens. Also if you don't know the LANG YOUR TRYING TO INTEGRATE WITH, don't use it 💀
