### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by BloodyToolzz** [addi00000/empyrean#23]
I get this error everytime I attempt to compile:

```python
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\zeesh\\AppData\\Local\\pyinstaller\\bincache01_py310_64bit\\crypto\\publickey\\_ec_ws.pyd'
```
I get the same error for some other files too which I didn't have enough time to see it."
Here is the full error at the end.
![image](https://user-images.githubusercontent.com/106907415/182101992-7df59698-7399-47a3-9a13-d710c61fed48.png)

**Comment by BloodyToolzz** [comment]
Oh nvm my fucking gay Antivirus detected it and and deleted it, that's why, AND IT NEVER LET ME KNOW IT DETECTED IT, SO GAYYYYYYYYY

**Comment by addi00000** [comment]
windows defender or something else?

**Comment by BloodyToolzz** [comment]
> windows defender or something else?

Avast

**Comment by GodFather227** [comment]
> > windows defender or something else?
> 
> Avast

anti virus = basically useless. The best av is yourself (not being a dumbass)

**Comment by BloodyToolzz** [comment]
> > > windows defender or something else?
> > 
> > 
> > Avast
> 
> anti virus = basically useless. The best av is yourself (not being a dumbass)

Yes.
