### ISSUE TITLE
Sends Webhook info about random people.

### ISSUE THREAD

**Issue by Cryptic1526** [addi00000/empyrean#233]
I got a message on my Webhook channel even though I didn't send it to anyone except a friend, but it's not him. Its this random pc in Russia.

![image](https://user-images.githubusercontent.com/119151348/230705277-13e8c3cb-8cc6-429b-9dd1-e1ae9bb8de6d.png)

Just want to know how it's connecting to other people...

**Comment by 429565000161264517609635766710319130884** [comment]
RUN.APP

**Comment by HypixelModsQOL** [comment]
yea, i get them too. but i just ignore em.

**Comment by 429565000161264517609635766710319130884** [comment]
That happen because u upload ur exe file on an hosted file uploader that scan ur file

**Comment by CheatTerminator** [comment]
Same, I assume that those were tests from virustotal.
