### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rett0r3x** [addi00000/empyrean#240]
**Describe the bug**
Once entering all the information it stops while creating the environment showing this error

**To Reproduce**
1. Open builder.py
2. Enter your settings
3. Wait about 0.2s

**Expected behavior**
I expected it to create the build folder but it doesn't because it stops at creating environment

**Screenshots**
![obraz_2023-04-15_145230959](https://user-images.githubusercontent.com/130842774/232224786-b8c221a2-0eb8-42eb-a1ac-57ed396060c9.png)

**Additional context**

**Comment by Rett0r3x** [comment]
dist folder*

**Comment by Lunarhub-V3** [comment]
yea i get same issue
