### ISSUE TITLE
[BUG] The builder won't build the exe

### ISSUE THREAD

**Issue by Bandu42794** [addi00000/empyrean#245]
**Describe the bug**
Whenever I use the builder, the builder won't build the executable.

**To Reproduce**
1. Build the exe
2. Build the exe
3. Build the exe
4. Build the exe

**Expected behavior**
An exectuable

**Screenshots**
![image](https://user-images.githubusercontent.com/116642014/232325607-f9e12e24-b992-4aab-bd36-d0b974df7c2b.png)

**Additional context**
The executable isn't building

**Comment by Bandu42794** [comment]
bro

**Comment by ThatOneGuy556** [comment]
> bro

i dont even have a dist folder its just ''build''
