### ISSUE TITLE
Epyrean bug

### ISSUE THREAD

**Issue by Fuseeee** [addi00000/empyrean#246]
I don't get this 
![image](https://user-images.githubusercontent.com/130925710/232331667-f345d1ff-3aea-4838-802d-4b81ba2afb53.png)
and this
![image](https://user-images.githubusercontent.com/130925710/232331678-18b22bf6-56c3-41be-b58a-f6171720e419.png)
and i want to know why ?

**Comment by Fuseeee** [comment]
@addi00000

**Comment by FastZer** [comment]
yeah, me too

**Comment by FastZer** [comment]
nvm i did it again and it works
