### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 2, in <module>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module   File "components\browsers.py", line 8, in <module> ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by HRT9014** [addi00000/empyrean#250]
When i open the exe file in dist it it open a error thing and says :

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "components\browsers.py", line 8, in <module>
ModuleNotFoundError: No module named 'Crypto'

even as administrator

**Comment by Dorkerdotcom** [comment]
open command prompt and run this where the txt file si in: pip install -r requirements.txt
