### ISSUE TITLE
[BUG] No dist folder and build error.

### ISSUE THREAD

**Issue by Lunarhub-V3** [addi00000/empyrean#258]
**Describe the bug**
After i install the requirements there is no " dist " folder. And when i try building it says that it doesnt work because of no dist folder.

https://prnt.sc/wtEkPzoojQ3l (no dist folder after installing requirements.txt)
https://prnt.sc/MsSo2WhJWNFP (The error when i try to build it)

And i did everything correctly. I tried restaarting pc, reinstalling python and git, Nothing helped. Please help me fix this issue.

**Comment by NegroOfMorias** [comment]
hello , I have the same problem , could someone help a bit @addi00000 @Lunarhub-V3
