### ISSUE TITLE
Passwords Not Sending

### ISSUE THREAD

**Issue by PorpyWasTaken** [addi00000/empyrean#26]
here is a bug in your grabber where when you run the stub it doesnt send the txts of the passwords  to the webhook but instead just copies them to the directory which the file was run on

**Comment by GodFather227** [comment]
> here is a bug in your grabber where when you run the stub it doesnt send the txts of the passwords to the webhook but instead just copies them to the directory which the file was run on

That isn’t a bug. It’s an issue on your end. And quit calling an executable a stub that shits mad annoying
