### ISSUE TITLE
what do i do if i run it on myself to test it

### ISSUE THREAD

**Issue by yohantm2131** [addi00000/empyrean#266]
if i ran it on myself, does it do anything? i saw it did some run.bat stuff but how do i negate the effects of what it did if you understand?

**Comment by Lunarhub-V3** [comment]
The only thing it does is send your credentials, cookies, etc. But if your gonna try it on yourself i recommend turning discord injection off and auto startup off.

**Comment by dfluder** [comment]
I tested this software on myself a long time ago, but if I remember right you need to delete the "empyrean" folder located in %appdata%/Roaming
I don't think it was creating a .js file in your discord directory but I'm not sure - I cant remember the exact location but there should be a .js file larger than 1kb with the "injection" code so every time you are changing something - its popping up with the credentials (or its just the .exe working in background) Correct me if I'm wrong :)

**Comment by vobz12** [comment]
> The only thing it does is send your credentials, cookies, etc. But if your gonna try it on yourself i recommend turning discord injection off and auto startup off.

yo I accidentely opened the file, how d o Iremove auto startup and auto discord injection

**Comment by dfluder** [comment]
> > The only thing it does is send your credentials, cookies, etc. But if your gonna try it on yourself i recommend turning discord injection off and auto startup off.
> 
> yo I accidentely opened the file, how d o Iremove auto startup and auto discord injection

click WIN + R and type %appdata% - there u will find a folder called Empyrean - delete it
Im not sure about the discord injection because i was not using this tool for longer than 5 minutes

**Comment by BrownSheepie2021** [comment]
> > > The only thing it does is send your credentials, cookies, etc. But if your gonna try it on yourself i recommend turning discord injection off and auto startup off.
> > 
> > 
> > yo I accidentely opened the file, how d o Iremove auto startup and auto discord injection
> 
> click WIN + R and type %appdata% - there u will find a folder called Empyrean - delete it Im not sure about the discord injection because i was not using this tool for longer than 5 minutes

there isnt a folder for me there
