### ISSUE TITLE
cannot import name 'RequestWebhookAdapter' from 'discord'

### ISSUE THREAD

**Issue by MintOnTop** [addi00000/empyrean#27]
It says much code and any other information I think and no message is sent to the server with the webhook. Anyone got a idea how to fix this?
![Screenshot 2022-08-20 160755](https://user-images.githubusercontent.com/96620548/185750222-2c3624dc-3495-48cf-85ae-890a3aedb8c5.png)

**Comment by MintOnTop** [comment]
And it also says if I try to build the .exe something like this in red: 
COULD NOT FIGURE A C COMPILER

I don't know if that's important...

**Comment by addi00000** [comment]
This is an issue with the new discord.py update. Working to fix.
