### ISSUE TITLE
[BUG] Webhook Not Working

### ISSUE THREAD

**Issue by edicot4** [addi00000/empyrean#277]
(Tested on my self) Once run the application supposedly does something as it closes my discord but when i check my channel for the token etc theres nothing there. 
Does anyone  know a fix or is it just a program that steals your information and sends it to the creator?

**Comment by edicot4** [comment]
never mind, i got the webhook to send my systems info and a vault but the discor users token, email and pass are still missing. Please let me know if theres a fix :D

**Comment by edicot4** [comment]
i got my victim to send me the files that the sofware gave him and it had all the files for the cookies etc but one thing i noticed is that it was all messed up. It looked like; 
SQLite format 3   @   p­  â       Ÿ                                                  p­ ._
	Ã  ! gÏ !œœ	{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                   …
 ŠtablecookiescookiesCREATE TABLE cookies(creation_utc INTEGER NOT NULL,host_key TEXT NOT NULL,top_frame_site_key TEXT NOT NULL,name TEXT NOT NULL,value TEXT NOT NULL,encrypted_value BLOB NOT NULL,path TEXT NOT NULL,expires_utc INTEGER NOT NULL,is_secure INTEGER NOT NULL,is_httponly INTEGER NOT NULL,last_access_utc INTEGER NOT NULL,has_expires INTEGER NOT NULL,is_persistent INTEGER NOT NULL,priority INTEGER NOT NULL,samesite INTEGER NOT NULL,source_scheme INTEGER NOT NULL,source_port INTEGER NOT NULL,is_same_party INTEGER NOT NULL,last_update_utc INTEGER NOT NULL, is_edgelegacycookie INTEGER NOT NULL DEFAULT 0, browser_provenance INTEGER NOT NULL DEFAULT 0)
$Ù                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5Gindexcookies_unique_indexcookiesCREATE UNIQUE INDEX cookies_unique_index ON cookies(host_key, top_frame_site_key, name, path)øC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               f /tablemetametaCREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR)'; indexsqlite_autoindex_meta_1meta       
   … î©…àÂ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   " Icompatible_edge_version_number33edge_version_number3;last_compatible_version18version18#mmap_status-1
   Ž Ž±Éñå                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Icompatible_edge_version_number 3edge_version_number;last_compatible_versionversion#	mmap_status
n fKäÉ®“w\=	;þÛ¹{\>"
ÿ
Ò
¶
˜
s
M
(
ðÏ°ˆc:üÛ¾œ…eI%
ä
¬
r
9	þ	à	z	÷Ö¬…[0u  5 ä Ë	½K u P ø×Àªw	[ŽX2çÂ¢…d$éÑ²ˆ^# ¹q5ðÊ­uTîÑ¶                                                                             	¢                 "%

**Comment by edicot4** [comment]
ive concluded that it doesnt send anyone elses logs but yours

**Comment by edicot4** [comment]
any fixes?

**Comment by xpierroz** [comment]
> i got my victim to send me the files that the sofware gave him and it had all the files for the cookies etc but one thing i noticed is that it was all messed up. It looked like; SQLite format 3 � �� @ �p­ �â Ÿ � � � �p­ ._� Ã � ! �g�Ï !œœ { ��� …� ����Š�tablecookiescookies�CREATE TABLE cookies(creation_utc INTEGER NOT NULL,host_key TEXT NOT NULL,top_frame_site_key TEXT NOT NULL,name TEXT NOT NULL,value TEXT NOT NULL,encrypted_value BLOB NOT NULL,path TEXT NOT NULL,expires_utc INTEGER NOT NULL,is_secure INTEGER NOT NULL,is_httponly INTEGER NOT NULL,last_access_utc INTEGER NOT NULL,has_expires INTEGER NOT NULL,is_persistent INTEGER NOT NULL,priority INTEGER NOT NULL,samesite INTEGER NOT NULL,source_scheme INTEGER NOT NULL,source_port INTEGER NOT NULL,is_same_party INTEGER NOT NULL,last_update_utc INTEGER NOT NULL, is_edgelegacycookie INTEGER NOT NULL DEFAULT 0, browser_provenance INTEGER NOT NULL DEFAULT 0) $�Ù ��� �5���Gindexcookies_unique_indexcookies�CREATE UNIQUE INDEX cookies_unique_index ON cookies(host_key, top_frame_site_key, name, path)�ø�C f� �����/tablemetameta�CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR)'���;�� indexsqlite_autoindex_meta_1meta� � ��… �î�©�…�à�Â " �I�compatible_edge_version_number3���3�edge_version_number3���;�last_compatible_version18����version18���#�mmap_status-1 ��Ž �Ž�±�É�ñ�å "�I�compatible_edge_version_number ��3�edge_version_number���;�last_compatible_version�����version���# mmap_status �n f�K��ä�É�®�“�w�\�=�� ;�þ�Û�¹�{�\�>�" ÿ Ò ¶ ˜ s M ( �ðÏ°ˆc:��ü�Û�¾�œ�…�e�I�% ä ¬ r 9 þ à z ��÷�Ö�¬�…�[�0�u� 5 ä Ë ½�K u P ��ø�×�À�ª�w [�Ž�X�2���ç�Â�¢�…�d�$���é�Ñ�²�ˆ�^�#� �¹�q�5���ð�Ê�­���u�T���î�Ñ�¶������������������������ ¢ � "�%

this is SQL readable stuff, use https://sqlite.org/index.html to open it
