### ISSUE TITLE
NOT A BUG!

### ISSUE THREAD

**Issue by Johann12jj** [addi00000/empyrean#280]
The system runned smoothly but im having truble on how to send it to a victim idk how to send it ,is there any link to send it to a victim?? or smting <please help me>

**Comment by Johann12jj** [comment]
how to send it to a victim pls reply>>>

**Comment by otema666** [comment]
Chaval, estas de coña?

**Comment by LordCrestfallen** [comment]
Learn how to lie to people, kid.
