### ISSUE TITLE
Unable to complete Install [ISSUE]

### ISSUE THREAD

**Issue by vmo0t2xw00t** [addi00000/empyrean#299]
Windows 11

Received error: 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "components\browsers.py", line 9, in <module>
ModuleNotFoundError: No module named 'Crypto'

Referenced previous [thread](https://github.com/addi00000/empyrean/issues/250) and  did the following:

open command prompt and run this where the txt file is in: pip install -r requirements.txt

Re-ran build.bat and subsequent created main.exe, received same error.

Any assistance is greatly appreciated.

**Comment by vmo0t2xw00t** [comment]
Ran cmd, said it was already installed...
<img width="316" alt="image" src="https://github.com/addi00000/empyrean/assets/131321792/46bd83ab-388f-4e41-99b3-b72b4eb757e2">

Got this message after running .bat and getting a new .exe
<img width="304" alt="image" src="https://github.com/addi00000/empyrean/assets/131321792/299a0e5a-caf9-4110-b14e-284f66cf95e3">

**Comment by Cyber-Dioxide** [comment]
`pip install cryptography`

`pip install pycryptodome`
After you install the pycryptodome package, try importing it as follows.
main.py
`
from Crypto.Cipher import AES

from Crypto.Random import get_random_bytes

data = b'secret data'

key = get_random_bytes(16)
cipher = AES.new(key, AES.MODE_EAX)
ciphertext, tag = cipher.encrypt_and_digest(data)

file_out = open("encrypted.bin", "wb")
[file_out.write(x) for x in (cipher.nonce, tag, ciphertext)]
file_out.close()`

Still if you are facing this error contact me on instagram **i@coding_memz**
