### ISSUE TITLE
not a bug, how to remove it from my computer?

### ISSUE THREAD

**Issue by BrownSheepie2021** [addi00000/empyrean#300]
ok so im stupid and ran it on my computer, and the webhook isnt replying or sending messages is there a way to remove this thing?

**Comment by yxvi** [comment]
turn on antivirus or find the virus

**Comment by MrPondi** [comment]
remove startup from the registry and reinstall discord

**Comment by Procoder549** [comment]
> ok so im stupid and ran it on my computer, and the webhook isnt replying or sending messages is there a way to remove this thing?

windows + r
shell:common startup
delete all the .scr files

**Comment by idk18282838** [comment]
i know its kinda late but click windows+R then type in %appdata% and delete the folder called empyrean
