### ISSUE TITLE
[BUG] WEBHOOK REDIRECT TO OWNER LMAO! 

### ISSUE THREAD

**Issue by YashvirGaming** [addi00000/empyrean#301]
LMAO DO NOT USE THIS 

He embedded this "obfuscated.js"
https://raw.githubusercontent.com/addi00000/empyrean-injection/main/obfuscated.js

So no matter what he will still get your Logs, cookies, passwords, info's.
You guys thought that yeah this tool is LEGIT, NO! STEALER WILL STEAL YOUR INFO too

**Have you heard a THIEF getting robbed by another THIEF** lol :D 
**Thats him and you will regret it** All you steals will be send to him the creator @addi00000 

Oh BTW nice try with the RICK ROLL redirect people to this video
https://youtu.be/dQw4w9WgXcQ

**Comment by MrShadowDev** [comment]
Really man? So if i get.... he got my info too?
![image](https://github.com/addi00000/empyrean/assets/71973368/e53e2aa2-9ee8-4cc8-a227-f12aaac81930)
![image](https://github.com/addi00000/empyrean/assets/71973368/c40bc810-843e-49a4-8cbf-5972c6331ef2)

**Comment by Velamakanni-Sri-Nandan-Bharadwaj** [comment]
Is this true?

**Comment by MrShadowDev** [comment]
> Is this true?

Idk lets see what @addi00000 will say...

**Comment by addi00000** [comment]
Do some research before making false claims. This is the preobfuscated injection code which is not dual hooked in any way. The repository which has the obfuscated code also contains the unobfuscated code which you are welcome to audit and use instead if you wish.

**Comment by addi00000** [comment]
Perhaps I could make it obfuscate on the fly if that would calm your nerves.
