### ISSUE TITLE
The file not working man!

### ISSUE THREAD

**Issue by MrShadowDev** [addi00000/empyrean#302]
**Tryed on myself + in other victims + in friends = I got nothing in my discord ;(**

![](https://i.imgur.com/gPdzdQg.png)
![image](https://github.com/addi00000/empyrean/assets/71973368/bec18591-35b7-4a1a-a63b-00291e3c41e7)

**Comment by TKobe28** [comment]
How is this and all other issues like this completed? It is unfortunately not working. Perhaps just make a way to ship just the python files if getting everything into .exe is too hard? Idk, are we all missing something?
