### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named "Click"

### ISSUE THREAD

**Issue by joemama22222222222222** [addi00000/empyrean#305]
**Describe the bug**
program wont load properly 

**To Reproduce**
follow the instructions you provided to step 4, then see the console show the following
Traceback <most recent call last>:
File "C:\Users\joemama\Desktop\discord trolling shit\empyrean-main\builder\main.py", line 3, in <module>
     import click
ModuleNotFoundError: No module named 'click'
Press any key to continue .  .  .
**Expected behavior**
i expected to be able to see a dist folder (doesnt exist) and be able to interact with a main.py 

![image](https://github.com/addi00000/empyrean/assets/136772717/aeae6a9c-d0a2-4a15-84c9-bdbd6c57fa5a)

**Additional context**

**Comment by phreakyphoenix** [comment]
@joemama22222222222222 
Use `pip install -r requirements.txt`
You may need to use pip3 instead of pip depending on your setup.
Before running any python project you'd need to install the dependencies, which are in the requirements.txt file.

**Comment by joemama22222222222222** [comment]
> @joemama22222222222222 Use `pip install -r requirements.txt` You may need to use pip3 instead of pip depending on your setup. Before running any python project you'd need to install the dependencies, which are in the requirements.txt file.
how
