### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by H3lix-Fire** [addi00000/empyrean#32]
Maybe don't obfuscate the javascript used in injection, it's pretty suspicious.

**Comment by addi00000** [comment]
I can deobfuscate it but then anyone can see the full code and understand it’s malware

**Comment by H3lix-Fire** [comment]
> I can deobfuscate it but then anyone can see the full code and understand it’s malware

We can obfuscate it ourselves tho.

**Comment by Smug246** [comment]
> > I can deobfuscate it but then anyone can see the full code and understand it’s malware
> 
> 
> 
> We can obfuscate it ourselves tho.

i don't think many people want to have to obfuscate the injection themselves. anyways it would be better to just take the code from a repository instead so then they don't see it at all unless they get the github link

**Comment by addi00000** [comment]
I may do this but not for now because it doesnt make sense

**Comment by l3qso** [comment]
> I can deobfuscate it but then anyone can see the full code and understand it’s malware

can anyone deobfuscate it?
