### ISSUE TITLE
[BUG]Traceback (most recent call last):   File "main.py", line 8, in <module> ModuleNotFoundError: No module named 'components.injection'

### ISSUE THREAD

**Issue by kxcpusss** [addi00000/empyrean#326]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
ModuleNotFoundError: No module named 'components.injection'

what can I do?

**Comment by Azuuu1** [comment]
install the module

**Comment by kxcpusss** [comment]
I installed

**Comment by Azuuu1** [comment]
try to run it and it should work if it doesnt i dont know

**Comment by Azuuu1** [comment]
yo bro if u have dsc add me AzuuHold#5949 and i will try to help you there
