### ISSUE TITLE
Question regarding card grabbing

### ISSUE THREAD

**Issue by LordCrestfallen** [addi00000/empyrean#340]
![image_2023-08-07_234815812](https://github.com/addi00000/empyrean/assets/131706299/c6b62135-b2f9-46db-9109-639dcc2709be)

What do the 1679236350 and 11 mean? I'm not seeing a CVV so I don't really see the point unless I'm missing something. This is the 3rd time I've seen a grabbed card look like this.

**Comment by LordCrestfallen** [comment]
![image_2023-08-07_235102794](https://github.com/addi00000/empyrean/assets/131706299/1b7640ae-5f8d-4615-b69e-9d1a3b997669)

Another example. Thank you.

**Comment by sdGGDSBSDVB** [comment]
mines doesnt grab the card at all

**Comment by LordCrestfallen** [comment]
> mines doesnt grab the card at all

They probably don't have any cards that the grabber can find.

**Comment by addi00000** [comment]
Format is as follows: name on card, month, year, card number, added timestamp

Additionally, chrome does not store the cvv so we are unable to get it.

**Comment by LordCrestfallen** [comment]
Thank you for the response, addi.

A few months ago, I wanted to work on a CVV finder but lost motivation. Do you know any way to find the CVV or is that basically impossible?
