### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 0xAnonymx0** [addi00000/empyrean#341]
Can Someone help me Like i dont understand the problem here.
I reinstald it and looked in the files.
The code is available .(line 3)
(https://github.com/addi00000/empyrean/assets/142009320/9847ed42-47e5-42d5-9872-76c76c4c75cf)

**Comment by ibnaleem** [comment]
```shell
$ pip install click
```

**Comment by 0xAnonymx0** [comment]
can u maybe give your dc and help me bro?

**Comment by ibnaleem** [comment]
1. Open `Command Prompt`
2. Type `pip install click`
3. Run the script again

**Comment by 0xAnonymx0** [comment]
should open the normal cmd or where?

**Comment by ibnaleem** [comment]
normal

**Comment by 0xAnonymx0** [comment]
![image](https://github.com/addi00000/empyrean/assets/142009320/ce20957b-d9d3-454a-98e6-64a2ea83d15a)
dosnt work bro

**Comment by ibnaleem** [comment]
translate

**Comment by 0xAnonymx0** [comment]
the normal errror :
The command is flase written or cant be finded

**Comment by 0xAnonymx0** [comment]
Was my pcs problem
