### ISSUE TITLE
No Token/Discord Infos

### ISSUE THREAD

**Issue by 0xAnonymx0** [addi00000/empyrean#343]
I ran it on my Pc but i get no Dc info. 
(I use discord in browser)
Can it be the reason why  i get no dc informations?

**Comment by 0xAnonymx0** [comment]
Or like is it a bug i have no Idea.

**Comment by Fydren** [comment]
prob fake delete it

**Comment by 0xAnonymx0** [comment]
no bro i get the infos in my discord bit no Discord/Token Information
