### ISSUE TITLE
What happens to the data of the victims and is it copied elsewhere?

### ISSUE THREAD

**Issue by imperialisticRSPS** [addi00000/empyrean#359]
Recently I ran the file on myself for testing purposes to ensure that it worked, however it never dawned on me for the fact it sends a zip via webhook with the data. Where is this information processed at and where has it been stored? I'm referring to outside of our pcs. Is that data "safe" and I use that word lightly due to the nature of things here, but between myself(stub creator) and victim? Or now that it's been processed and zipped, does someone else out there have that information such as yourself or was it publicly posted somewhere? A genuine answer would be much appreciated. 
@addi00000

**Comment by addi00000** [comment]
The zip is compiled on the victims computer and uploaded to discord's cdn via the webhook.
