### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by frigiate** [addi00000/empyrean#369]
whenever i try to load up main.exe i get this error code

Traceback (most recent call last):
  File "main.py", line 6, in <module>
ModuleNotFoundError: No module named 'components.browsers'

i tried pip installing a bunch of stuff but it said they dont exist. 
I also have only these files in my components folder

antidebug.py
startup.py
systeminfo.py

**Comment by Bang-Bang-Ban** [comment]
antivirus removed the file because its quite malicious, add an exception to the folder when you unzip it

**Comment by bekreative6** [comment]
i am getting this error, how can i fix it?

**Comment by rafaeltamado** [comment]
i am getting this error, how can i fix it?
