### ISSUE TITLE
[BUG] command prompt opens, any error but not the fake error and no system information

### ISSUE THREAD

**Issue by Gumbobrot** [addi00000/empyrean#37]
![unknown](https://user-images.githubusercontent.com/96620548/189497298-dc9afeb4-4bac-4611-acad-5b557e812873.png)
I compiled the file and when I executed that error popped up and it's not the fake error, because I didn't tick that when compiling. Also, after every start up a system 32 command prompt opens. And the discord webhook is only showing files and discord information but no system information. Please give me some advice how I can remove that cuz it's really annoying after every startup and fix it. I really really need the grabber right now.

**Comment by MintOnTop** [comment]
Hey it's me again, maybe you could add a option that you can directly see the geo location of someone and it would be amazing if you add something thats shows the WinKey, City and Region (just a suggestion, would be really cool, but for now I would prefer just a working grabber. I like that grabber and it would be good for me if the grabber works again, I've reported the bug two days ago)

**Comment by 140hermione** [comment]
go C:\Users\"user name"\AppData\Local\Temp
and search empyrean-vault
delete files 
Then open it again

**Comment by MintOnTop** [comment]
okay thanks, I'll try it...

**Comment by addi00000** [comment]
Had this issue on the discord server. It was solved thru a workaround involving WMIC being broken. I may have to remove the wifi passwords feature to fix this permanatley.

**Comment by MintOnTop** [comment]
> go C:\Users"user name"\AppData\Local\Temp and search empyrean-vault delete files Then open it again

hey I tried but there are like 100 files and I cant find empyrean-vault in there

**Comment by MintOnTop** [comment]
> Had this issue on the discord server. It was solved thru a workaround involving WMIC being broken. I may have to remove the wifi passwords feature to fix this permanatley.

uh can you explain how I can fix this for my computer (I grabbed myself and have the bug with the command promt now)
