### ISSUE TITLE
Am I paranoid or retarded or both?[BUG]

### ISSUE THREAD

**Issue by RealShadowHive** [addi00000/empyrean#372]
So I just wanted to use this tool to mess a little bit with one of my friends on discord. When I opened the main batch file Microsoft Defender suddenly started screaming at me that it has a new threat detected, which was called Zkarletflash. So I thought to myself better be safe than sorry and install this whole thing in a VM, so I went to delete the empyrean folder but the Windows Defender Warning still remained, even after restarting my PC nothing changed. The fact that the defender does exactly nothing even when I click on remove or quarantine is also kinda worrysome. Anyone know how to get rid of this warning, I cant even click on allow to make it go away.

Also could my discord account get banned for this if my friend deceides to report me for this?

**Comment by Bang-Bang-Ban** [comment]
open defender and see where it says threats found, then remove them, its not a virus its open source 🤪  !!
