### ISSUE TITLE
[BUG]ERROR: Package 'pyinstaller' 

### ISSUE THREAD

**Issue by Dav1dV2** [addi00000/empyrean#374]
ERROR: Package 'pyinstaller' requires a different Python: 3.12.0 not in '<3.11,>=3.7'
![image](https://github.com/addi00000/empyrean/assets/149514364/03a6068e-4231-4766-ac33-a6f02bf9b8ce)
 how do i fix this?

**Comment by Dav1dV2** [comment]
WHAT TO DO?!

**Comment by MGTro** [comment]
try running install_python.bat

**Comment by Dav1dV2** [comment]
Thanks. worked
is there an option to change the file logo?
