### ISSUE TITLE
[BUG] No C compiler when compiling PyInstaller bootloader.

### ISSUE THREAD

**Issue by 140hermione** [addi00000/empyrean#39]
how do to fix it? 
![image](https://user-images.githubusercontent.com/111866023/189815276-5e493c0b-f215-48a5-b58c-9b36182fbf64.png)
'all' finished successfully (0.001s)
'distclean' finished successfully (0.001s)
Setting top to                           : C:\Users\king\Desktop\tools\empyrean\buildenv\pyinstaller\pyinstaller-5.1\bootloader
Setting out to                           : C:\Users\king\Desktop\tools\empyrean\buildenv\pyinstaller\pyinstaller-5.1\bootloader\build
Python Version                           : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : not found
Checking for 'gcc' (C compiler)          : not found
Checking for 'clang' (C compiler)        : not found
could not configure a C compiler!
(complete log in C:\Users\king\Desktop\tools\empyrean\buildenv\pyinstaller\pyinstaller-5.1\bootloader\build\config.log)

**Comment by addi00000** [comment]
- Try installing a c compiler (gcc, clang, etc...)
- Try uninstalling and reinstalling python (3.10.5)

**Comment by 140hermione** [comment]
thanks bro
