### ISSUE TITLE
[FEAT.] Send to telegram bot as an option

### ISSUE THREAD

**Issue by Choomai** [addi00000/empyrean#391]
**Is your feature request related to a problem? Please describe.**
I got my discord account banned for using this.

**Describe the solution you'd like**
Switching to Telegram bot should be better.

**Additional context**: None

**Comment by addi00000** [comment]
No plans to do this as of currently since it would require a semi-major code refactor. If anyone is willing to make a pull request I wouldn't mind accepting it.

**Comment by addi00000** [comment]
This is a FAQ so i will pin this issue
