### ISSUE TITLE
[BUG]Detectable by windows defender, any tips how to obfuscate?

### ISSUE THREAD

**Issue by Kubakuba12** [addi00000/empyrean#394]
self-describing

**Comment by Bildcraft1** [comment]
use something like VMProtect/UPX for packing it

**Comment by freikugelex** [comment]
> use something like VMProtect/UPX for packing it

tried VMProtect, doesn't seem to work (or i just may be retarded) and I thought empyrean already uses UPX to pack the exe? Any other ways to get windows defender to not flag it, or atleast have the download in browser go through?
