### ISSUE TITLE
Got a hit but never distributed the program...

### ISSUE THREAD

**Issue by D4rkdr4gonpy** [addi00000/empyrean#395]
![weird](https://github.com/addi00000/empyrean/assets/153268018/a2491e56-eb71-4e97-9aad-baa19d88ef78)
So this is really weird. I made my empyrean exe and tested it out on my own machine (because I just wanted to test it). A day or so later I get a hit, but I never distributed the exe file. I'm just a bit freaked out and hope someone can help me, thanks.

The attached image is the screenshot I got

Anyone recognize this:

User:
Display Name: Abby
Hostname: WIN-5E07COS9ALR
Username: Abby

System:
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
GPU: Microsoft Hyper-V Video
RAM: 1.0
HWID: 11111111-2222-3333-4444-555555555555

network:
IP Address: 20.99.160.173
MAC Address: 00:15:5d:00:19:81
Country: US
Region: Washington
City: Quincy (98848)
ISP: AS8075

**Comment by gumbobr0t** [comment]
its a vm, his avm is outdated ig
