### ISSUE TITLE
[BUG] blocked by microsoft defender anyone got a fix?

### ISSUE THREAD

**Issue by koskair** [addi00000/empyrean#403]
Window defender being a bitch and I cant get through it or im just retarded.

**Comment by OGApex** [comment]
Happens when you skid malware and have no idea how to bypass AVs.

**Comment by koskair** [comment]
I need to obfuscate ik but i dont really wanna pay for a program. Also yeah Im a skid, cant be bothered to fully fucking learn python and all the shit needed for it.

**Comment by koskair** [comment]
Yeah Ik im a skid but like I could be bothered to learn python and get programs to obfuscate or wtv.

**Comment by koskair** [comment]
Maybe someone could teach me how to make obfuscation program by using c#, hmmm I wonder who. See this is the thing a lot of skids dont have the material or time to learn programming languages, however someone like you who goes to college and is making there own C# Obfuscation program has learnt all they need to know. Its a matter of time and I cant be fucked to wait until im in college or wtv.

**Comment by koskair** [comment]
Also its obfuscated by upx so .....
