### ISSUE TITLE
[BUG] Webhook is trying to use emojis, but not working

### ISSUE THREAD

**Issue by Gumbobrot** [addi00000/empyrean#41]
![Screenshot_20220918-172921_Discord](https://user-images.githubusercontent.com/96620548/190915432-194ccd2b-874c-4732-b69e-afff0f294d61.jpg)
I have already reported this bug on the Discord (and some other bugs), but I don't know if you've seen this.

yeah I know it's no big problem but would be great if you fixed this...

**Comment by addi00000** [comment]
Try on computer

**Comment by Gumbobrot** [comment]
I alreary did that. It's the same thing on my pc.

**Comment by Gumbobrot** [comment]
hello??

**Comment by StarNumber12046** [comment]
also for me

**Comment by Dinosaurum** [comment]
your using an extremely outdated vers then lol

**Comment by Dinosaurum** [comment]
@addi00000

**Comment by addi00000** [comment]
This is a necropost. Please make a new issue and document the errors
