### ISSUE TITLE
[FEAT.] Own Epic Games, Minecraft, Roblox files

### ISSUE THREAD

**Issue by Gumbobrot** [addi00000/empyrean#44]
Heyy!! I would like to suggest that you could maybe add it's own special game files for games like Roblox, Minecraft or Epic Games which sent the data and other stuff through the empyrean-vault to the webhook. I think that would be pretty nice for some people!

**Comment by Smug246** [comment]
this is a good idea @Gumbobrot and the things your saying to both mine and addidix's grabbers are great but your asking us both to enhance the same things. what i'm tryna say is we don't want identical grabbers that look different.

**Comment by addi00000** [comment]
roblox is already grabbed thru browser cookies and can be searched for and I see no actual use for Minecraft and epic games data so will not be implementing it.

**Comment by OmorOrNot** [comment]
wb steam?
