### ISSUE TITLE
Possibly better build method? (detections)

### ISSUE THREAD

**Issue by toastbestraw** [addi00000/empyrean#45]
Hello, I've tested the build that's given by default (Pyinstaller, etc), however since Pyinstaller is not the best for building exe files, I was wondering whether [Nuitka ](https://github.com/Nuitka/Nuitka)would work better.
I've used this and it has a lower rate of Virustotal detections; the number might lower in the future given it's updated regularly by a company.

Not quite sure how it would be built into the build file since there's also compilers being used in the original project.
Just something I thought would be useful as it could result in a better outcome.

**Comment by Smug246** [comment]
nuitka takes years to build.

**Comment by addi00000** [comment]
I may look into this in the future.

**Comment by 6nz** [comment]
> nuitka takes years to build.

Probably bc u dont know how to use Nuitka

**Comment by Smug246** [comment]
> > nuitka takes years to build.
> 
> Probably bc u dont know how to use Nuitka 

i tested it and built it with -one file. it took 15 minutes to build.

**Comment by 6nz** [comment]
> > > nuitka takes years to build.
> > 
> > Probably bc u dont know how to use Nuitka 
> 
> i tested it and built it with -one file. it took 15 minutes to build.

Lmao thats why it takes 15 mins 💀

**Comment by 6nz** [comment]
I dont have any issues CPU: I9 12th gen, multi processing enabled

**Comment by 6nz** [comment]
Max 5 mins

**Comment by Smug246** [comment]
> Max 5 mins

lmao that says it all. you have an i9 and it still takes 5 mins

**Comment by Smug246** [comment]
you can edit the code and change it to nuitka yourself or maybe he could have an option to compile with what one you choose

**Comment by addi00000** [comment]
> Max 5 mins

Send build command?

**Comment by 6nz** [comment]
> > Max 5 mins
> 
> Send build command?

nuitka --help

**Comment by 6nz** [comment]
> > > Max 5 mins
> > 
> > 
> > Send build command?
> 
> nuitka --help

https://nuitka.net/doc/user-manual.html

**Comment by Smug246** [comment]
> > > > Max 5 mins
> 
> > > 
> 
> > > 
> 
> > > Send build command?
> 
> > 
> 
> > nuitka --help
> 
> 
> 
> https://nuitka.net/doc/user-manual.html

he was asking for the one you use

**Comment by xor5** [comment]
> nuitka takes years to build.

You havn't installed the module cache lib
