### ISSUE TITLE
[BUG] Termed ? 💀

### ISSUE THREAD

**Issue by Zrivx** [addi00000/empyrean#49]
Server got termed ? 💀

**Comment by your-bestie** [comment]
ye you dumbshit, that or you just got banned cuz your gay ahahhaha

**Comment by addi00000** [comment]
https://discord.gg/J8b8uzwjbS new server

**Comment by Zrivx** [comment]
> ye you dumbshit, that or you just got banned cuz your gay ahahhaha

stfu mf nigger

**Comment by your-bestie** [comment]
> > ye you dumbshit, that or you just got banned cuz your gay ahahhaha
> 
> stfu mf nigger

stop fucking necroposting smfh
