### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by xor5** [addi00000/empyrean#51]
**Is your feature request related to a problem? Please describe.**
Detections

**Describe the solution you'd like**
Fucking use better obfuscation

**Additional context**
Use Nuitka please

**Comment by xor5** [comment]
1. obfuscate the code
2. compile using nuitka
3. done

**Comment by your-bestie** [comment]
lmao skid moment, do it yourself and make a pull request if that easy. Also no matter how hard you try it will always be reversible, its a interpreted lang. Make your own c++ grabber its not that hard and stop leaving shitty retarded issues

**Comment by xor5** [comment]
> lmao skid moment, do it yourself and make a pull request if that easy. Also no matter how hard you try it will always be reversible, its a interpreted lang. Make your own c++ grabber its not that hard and stop leaving shitty retarded issues

Actually, i was going to make a pull request, currently just testing it and also ALL langs no mater the type can be reversed, this just makes it harder to do so.
And by looking at your github profile you seems to have just fork'ed some public already shitty grabbers.
Please shut the fuck up, you are the real skid here.

-- xor7 (RandomVersion)

**Comment by your-bestie** [comment]
this isnt my main github for obvious reasons, i used it to fix rdimos cuz rdimos "modivation dropped faster than his dad left him" or smomething, 
>
also ALL langs no mater the type can be reversed
> 
lmao yes sure kid but reversing obfuscated c++ gives you some really hard to read assembly, compared to reversing interperated langs like python.
In python you can recover functions and logic and possibly even variable names, whereas mingw c++ will at best give you some pointers. 
Try it for yourself and see :)

**Comment by your-bestie** [comment]
also the fact that your dumb ass got banned from all the discord servers so you chill here and try to modify other peoples code when you have 1 star to your name instead of being useful to society is disappointing.

**Comment by xor5** [comment]
> also the fact that your dumb ass got banned from all the discord servers so you chill here and try to modify other peoples code when you have 1 star to your name instead of being useful to society is disappointing.

lol old acc got termed skid

**Comment by your-bestie** [comment]
> > also the fact that your dumb ass got banned from all the discord servers so you chill here and try to modify other peoples code when you have 1 star to your name instead of being useful to society is disappointing.
> 
> lol old acc got termed skid

sounds like a skill issue. All of the staffs accounts just got banned and we all came back, not you cuz literally everyone hates you.

**Comment by xor5** [comment]
cope

**Comment by your-bestie** [comment]
fr 😩

**Comment by Your-Bestie-Was-Banned** [comment]
why is this issue still open
