### ISSUE TITLE
[FEAT.]

### ISSUE THREAD

**Issue by Kloomey** [addi00000/empyrean#53]
My request's are, when the victim open the file all firewalls will be disabled, Real Time Protection will be disabled, The file will hide it self, the file will add itself to exclutions (so microsoft defender wont scan it) also an auto update feature

**Comment by xor5** [comment]
windows uac bypass 2024

**Comment by addi00000** [comment]
> windows uac bypass 2024

soz i only have 1997 method

**Comment by dlk6** [comment]
buy seroxen u brokies

**Comment by Your-Bestie-Was-Banned** [comment]
@Kloomey how tf do you think a multibillion dollar corperation is gonna allow that to run without av stopping

**Comment by brookslach** [comment]
> > 
> 
> seroxen is literally quasar(a free rat) 💀💀💀

too bad you can't read. (it's a heavily modified version)

**Comment by brookslach** [comment]
> buy seroxen u brokies

garbage rat either way
