### ISSUE TITLE
[FEAT.] Write cookies as dict

### ISSUE THREAD

**Issue by toastbestraw** [addi00000/empyrean#54]
**Is your feature request related to a problem? Please describe.**
There isn't really a problem, however, when working with cookies, it may be better to add them to a dict so we can use them with a cookie importer extension.

**Describe the solution you'd like**
Make the cookies that the file takes and add them to a dict so we can import them easily. Like below:
{
    "name:"
    "value:"
    "domain:"
},                      (list could go on).

**Additional context**
I've tested this with my own code and it worked, but I forgot to upload any kind of that code; so I don't have it anymore.
But to improve the cookies in this project would be good as you would have better knowlege since it's your code.
The code I made was just using f.write to write the "value:" etc, but adding the cookie.value after.

**Comment by Smug246** [comment]
there formatted with netscrape format so you can use an exporter that uses that

**Comment by addi00000** [comment]
formatted with the netscape standard not changing

closing
