### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vex-ss** [addi00000/empyrean#56]
,exec(__import__('marshal').loads(__5339__[1]+__8509__[1]+__4243__[1]+__9874__[1]+__7446__[1]+__7299__[1]+__5474__[1]+__3923__[1]+__2594__[1]+__6620__[1]+__1570__[1]+__8741__[1]+__1033__[1]+__1624__[1]+__2296__[1]+__9395__[1]+__6051__[1]+__1853__[1]+__5838__[1]+__9285__[1]+__5307__[1]+__8402__[1]+__2465__[1]+__5492__[1]+__6969__[1]+__5613__[1]+__4999__[1]+__2330__[1]+__3596__[1]+__2368__[1]+__9112__[1]+__8005__[1]+__5584__[1]+__4077__[1]+__4123__[1]+__6387__[1]+__4855__[1]+__8172__[1]+__3299__[1]+__3527__[1]+__3249__[1]+__9654__[1]+__7397__[1]+__5191__[1]+__9718__[1]+__4200__[1]+__2808__[1]+__5859__[1]+__6991__[1]+__8208__[1]+__2388__[1]+__5514__[1]+__5889__[1]+__6130__[1]+__5018__[1]+__9745__[1]+__9912__[1]+__6315__[1]+__5641__[1]+__8282__[1]+__7381__[1]+__9322__[1]+__5741__[1]+__6029__[1]+__7220__[1]+__7756__[1]+__4411__[1]+__3219__[1]+__9354__[1]+__9626__[1]+__4429__[1]+__7918__[1]+__3503__[1]+__8922__[1]+__1196__[1]+__9419__[1]+__1113__[1]+__4834__[1]+__7550__[1]+__9327__[1]+__3418__[1]+__3314__[1]+__2913__[1]+__3388__[1]+__1100__[1]+__1197__[1]+__9838__[1]+__4724__[1]+__4351__[1]+__9092__[1]+__7035__[1]+__4578__[1]+__5350__[1]+__4332__[1]+__9242__[1]+__5451__[1]+__3549__[1]+__3463__[1]+__3722__[1]+__3681__[1]+__2636__[1]+__8686__[1]+__5912__[1]+__8285__[1]+__2700__[1]+__5551__[1]+__1932__[1]+__6392__[1]+__8494__[1]+__5931__[1]+__7873__[1]+__2741__[1]+__5335__[1]+__8688__[1]+__7617__[1]+__4868__[1]+__4899__[1]+__9966__[1]+__3346__[1]+__7814__[1]+__3492__[1]+__4480__[1]+__7476__[1]+__7552__[1]+__7620__[1]+__6379__[1]+__3865__[1]+__3567__[1]+__9541__[1]+__4831__[1]+__1868__[1]+__5555__[1]+__3283__[1]+__8202__[1]+__7298__[1]+__9030__[1]+__3200__[1]+__2352__[1]+__9916__[1]+__6388__[1]+__6394__[1]+__8694__[1]+__6222__[1]+__2353__[1]+__7431__[1]+__7140__[1]+__2198__[1]+__1848__[1]+__8378__[1]+__3609__[1]),globals())
  File "Specter", line 4, in <module>
  File "Specter", line 4, in <lambda>
  File "<string>", line 31, in <module>
  File "C:\Python310\lib\site-packages\browser_cookie3\__init__.py", line 15, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'                     im not sure if this is a bug or something im doing wrong, lel plz help me

**Comment by KDot227** [comment]
> ,exec(**import**('marshal').loads(**5339**[1]+**8509**[1]+**4243**[1]+**9874**[1]+**7446**[1]+**7299**[1]+**5474**[1]+**3923**[1]+**2594**[1]+**6620**[1]+**1570**[1]+**8741**[1]+**1033**[1]+**1624**[1]+**2296**[1]+**9395**[1]+**6051**[1]+**1853**[1]+**5838**[1]+**9285**[1]+**5307**[1]+**8402**[1]+**2465**[1]+**5492**[1]+**6969**[1]+**5613**[1]+**4999**[1]+**2330**[1]+**3596**[1]+**2368**[1]+**9112**[1]+**8005**[1]+**5584**[1]+**4077**[1]+**4123**[1]+**6387**[1]+**4855**[1]+**8172**[1]+**3299**[1]+**3527**[1]+**3249**[1]+**9654**[1]+**7397**[1]+**5191**[1]+**9718**[1]+**4200**[1]+**2808**[1]+**5859**[1]+**6991**[1]+**8208**[1]+**2388**[1]+**5514**[1]+**5889**[1]+**6130**[1]+**5018**[1]+**9745**[1]+**9912**[1]+**6315**[1]+**5641**[1]+**8282**[1]+**7381**[1]+**9322**[1]+**5741**[1]+**6029**[1]+**7220**[1]+**7756**[1]+**4411**[1]+**3219**[1]+**9354**[1]+**9626**[1]+**4429**[1]+**7918**[1]+**3503**[1]+**8922**[1]+**1196**[1]+**9419**[1]+**1113**[1]+**4834**[1]+**7550**[1]+**9327**[1]+**3418**[1]+**3314**[1]+**2913**[1]+**3388**[1]+**1100**[1]+**1197**[1]+**9838**[1]+**4724**[1]+**4351**[1]+**9092**[1]+**7035**[1]+**4578**[1]+**5350**[1]+**4332**[1]+**9242**[1]+**5451**[1]+**3549**[1]+**3463**[1]+**3722**[1]+**3681**[1]+**2636**[1]+**8686**[1]+**5912**[1]+**8285**[1]+**2700**[1]+**5551**[1]+**1932**[1]+**6392**[1]+**8494**[1]+**5931**[1]+**7873**[1]+**2741**[1]+**5335**[1]+**8688**[1]+**7617**[1]+**4868**[1]+**4899**[1]+**9966**[1]+**3346**[1]+**7814**[1]+**3492**[1]+**4480**[1]+**7476**[1]+**7552**[1]+**7620**[1]+**6379**[1]+**3865**[1]+**3567**[1]+**9541**[1]+**4831**[1]+**1868**[1]+**5555**[1]+**3283**[1]+**8202**[1]+**7298**[1]+**9030**[1]+**3200**[1]+**2352**[1]+**9916**[1]+**6388**[1]+**6394**[1]+**8694**[1]+**6222**[1]+**2353**[1]+**7431**[1]+**7140**[1]+**2198**[1]+**1848**[1]+**8378**[1]+**3609**[1]),globals()) File "Specter", line 4, in File "Specter", line 4, in File "", line 31, in File "C:\Python310\lib\site-packages\browser_cookie3__init__.py", line 15, in from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto' im not sure if this is a bug or something im doing wrong, lel plz help me

pip install pycryptodome
