### ISSUE TITLE
run[BUG]

### ISSUE THREAD

**Issue by kamal89990** [addi00000/empyrean#62]
Hi, when I try to run the code by using./build.bat I got this error -

bash: ./build.bat: Permission denied

I installed all the required files & tried using the Sudo command but I got this error-

sudo: ./build.bat: command not found

and when i tryed to run the code by making it exicutable busing chmod it give me another error while exicuting the ./build.bat file -
./build.bat
./build.bat: line 1: @ECHO: command not found
./build.bat: line 2: @MODE: command not found
./build.bat: line 4: ECHO: command not found
./build.bat: line 5: ECHO: command not found
./build.bat: line 6: CLS: command not found
./build.bat: line 7: PAUSE: command not found

**Comment by kamal89990** [comment]
I had already tried that, but I am still getting this error:-
./build.bat: line 1: @ECHO: command not found
./build.bat: line 2: @MODE: command not found
./build.bat: line 4: ECHO: command not found
./build.bat: line 5: ECHO: command not found
./build.bat: line 6: CLS: command not found
./build.bat: line 7: PAUSE: command not found

**Comment by addi00000** [comment]
> so what are the steps to run this in a windows machine

on windows you just double click build.bat like a normal executable

**Comment by kamal89990** [comment]
thanks, it's installed, by the way, when are you going to make this compatible with lunex?

**Comment by addi00000** [comment]
not in the near future
