### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CerealXeno** [addi00000/empyrean#69]
so the bug is, after grabbing someone's info, it grabs their info ofc, but i notice it also leaks my own info, the host, which is kinda risky considering i would be in risk of my info getting leaked by a webhook in a server for d0xxing

**Comment by CerealXeno** [comment]
the question is, where does the startup is located

**Comment by addi00000** [comment]
> the question is, where does the startup is located

Roaming app data

**Comment by CerealXeno** [comment]
> > the question is, where does the startup is located
> 
> Roaming app data

So is it Empyrean/dat.txt or the batch file that I should remove to make it not start up run from my end, but start up run from the victim

**Basically what I'm saying, how to disable startup for me, but not disable start up for the victim.**

Is it empyrean and then

**Comment by CookieCodezz** [comment]
#69

**Comment by addi00000** [comment]
> > > the question is, where does the startup is located
> > 
> > 
> > Roaming app data
> 
> So is it Empyrean/dat.txt or the batch file that I should remove to make it not start up run from my end, but start up run from the victim
> 
> **Basically what I'm saying, how to disable startup for me, but not disable start up for the victim.**

just delete the folder
