### ISSUE TITLE
whoever runs this is an idiot

### ISSUE THREAD

**Issue by CookieCodezz** [addi00000/empyrean#71]
not gonna make a whole report why you shouldnt use this but long story short,
this logger contains various folders with files that are encoded and hid away
if you were to download this and extract this chances are that you will have loggers on your pc, i'd just copy the code and make my own repository and inspect it

like in line 18 in injection.py is incredibly suspicious were its importing this random js file that you dont know whats inside
just dont use skidded stuff on github, 13 year olds are extremely gullible and will do anything to make them look like a cool hacker
dont be one of them and just avoid sussy loggers that have 0 stars

(evidence below)
![image](https://user-images.githubusercontent.com/111982301/197596588-e807f637-68b3-403d-8eba-738b18daf487.png)
![image](https://user-images.githubusercontent.com/111982301/197596638-bab387c2-74b3-49b6-8e90-87e3b51b5220.png)

hopefully people can see this and start to use their brains for once instead of crying on issues how to install pip or something

**Comment by itsVrq** [comment]
> 

Bro This is clean version of decoded js, u can change url if u cant trust 
https://github.com/addi00000/empyrean-injection/blob/main/clean.js

**Comment by addi00000** [comment]
Above comment is correct.

**Comment by addi00000** [comment]
Then don’t

**Comment by itsVrq** [comment]
> still not trusting random shit on github

Who Cares, Who Asked ?

**Comment by Apophis52** [comment]
You are the stupidest person I have ever met. Just read the code.

**Comment by PandoricGalaxy** [comment]
> You are the stupidest person I have ever met. Just read the code.

he did have a point since even i dont understand the need to link to a injection url that is obfuscated but not our own, why is it even there in the first place?

**Comment by UiIsBack** [comment]
> > You are the stupidest person I have ever met. Just read the code.
> 
> he did have a point since even i dont understand the need to link to a injection url that is obfuscated but not our own, why is it even there in the first place?

its kind of obvious this is what copys into the grabbed users discord index.js file to be able to get the pass etc, and it’s obfuscated so no one gets your webhook

**Comment by Packjackisback** [comment]
Am I stupid or are they the same people. Mans having an argument with himself. Also he does this for basically every keylogger on github.

**Comment by addi00000** [comment]
> Am I stupid or are they the same people. Mans having an argument with himself. Also he does this for basically every keylogger on github.

ghost means the account was banned
so basically both were banned

**Comment by Packjackisback** [comment]
Ah lmao
