### ISSUE TITLE
[BUG] Phone Locked Tokens will raise errors

### ISSUE THREAD

**Issue by scoobyluvs** [addi00000/empyrean#76]
Simple mistake , made it myself. You need to change to check if the token is phone locked instead of returing ``200`` on its api code.
I suggest something like this 
```
if r.status_code == 200:
  // vaild
if r.status_code == 403:
  // phone locked
 ```
 should work , not all to sure tho 
 GL seems like a great project !

**Comment by addi00000** [comment]
It already accounts for and filters out non valid tokens here: https://github.com/addi00000/empyrean/blob/9f4a82b155b2892e755dac893957aa8e6d278d24/src/components/discordtoken.py#L103-L109

Is this an actual issue you are facing or theoretical

**Comment by scoobyluvs** [comment]
> It already accounts for and filters out non valid tokens here:
> 
> https://github.com/addi00000/empyrean/blob/9f4a82b155b2892e755dac893957aa8e6d278d24/src/components/discordtoken.py#L103-L109
> 
> Is this an actual issue you are facing or theoretical

This an actual issue , saw as here to https://github.com/addi00000/empyrean/issues/65

**Comment by scoobyluvs** [comment]
my bad i closed it
