### ISSUE TITLE
[BUG] Not Sending All Browser Data

### ISSUE THREAD

**Issue by Kimberly-Salazar** [addi00000/empyrean#78]
**Describe the bug**
Empyrean is sending only one browser data

**Expected behavior**
I expected it to send all the browser (like all edge brave etc...) to the webhook like the old version but in the new version it's not sending all of them just the chrome i guess

**Screenshots**
![image](https://user-images.githubusercontent.com/117445011/199951214-ccc584cb-529a-4a39-92dc-da0021085834.png)

**Comment by addi00000** [comment]
Not and issue. I have made it so all browser data is bundled into one file for each type. This change doesnt seem to be very popular so i may change it back.
