### ISSUE TITLE
[BUG] files not found :(

### ISSUE THREAD

**Issue by qPhantasm** [addi00000/empyrean#82]
![image](https://user-images.githubusercontent.com/96620548/203621942-48f518be-f6d9-4f0b-8d7c-4b5dfe964583.png)
still bugs :( i beg u to fix it..

**Comment by qPhantasm** [comment]
![image](https://user-images.githubusercontent.com/96620548/203622579-906ae253-1a73-4ce2-b21e-bac7aa6b8788.png)
kali is also not working :(

**Comment by qPhantasm** [comment]
![image](https://user-images.githubusercontent.com/96620548/203623009-048a5b81-029d-4464-99f0-034692338c60.png)
I also tried manually installing all the dependencies and then running the builder but I get this error...

**Comment by qPhantasm** [comment]
![image](https://user-images.githubusercontent.com/96620548/203623859-cebccfdb-9c24-4b50-9355-9657c74b6312.png)
dude, I also had to manually install InquirerPy, maybe add it to the req file, then I got it and ran the builder but I got the same fucking error

**Comment by addi00000** [comment]
> ![image](https://user-images.githubusercontent.com/96620548/203621942-48f518be-f6d9-4f0b-8d7c-4b5dfe964583.png) still bugs :( i beg u to fix it..

#83
