### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hajidoe** [addi00000/empyrean#85]
**Describe the bug**
Build fails for no reason & logger is not created.

![Screenshot 2022-11-23 214206](https://user-images.githubusercontent.com/118952303/203689061-429948bf-d624-44a1-b7b0-9864eb719d19.jpg)

**To Reproduce**
literally run Build.Bat
after you go through Y/N questions it shows the error.

**Expected behavior**
completely builds & creates a .exe file

**Additional context**
Webhook used: https://discord.com/api/webhooks/1045180427004022844/GpZQ_IRIIhu9SNVpvDmxZxhjltM8GMYJK3OaYsnhAG9QL-TEwt6MXfAJglVxuhD2EOE6

**Comment by addi00000** [comment]
Can you check if a build environment is being made named `build`. If exists please tree it and send results

**Comment by SecretSC** [comment]
> Can you check if a build environment is being made named `build`. If exists please tree it and send results

I got the same issue, please fix it.

![Capture](https://user-images.githubusercontent.com/54732748/203870088-2104477f-2f5b-4279-9fa1-bbd39fe9a8a9.PNG)

**Comment by addi00000** [comment]
> > Can you check if a build environment is being made named `build`. If exists please tree it and send results
> 
> I got the same issue, please fix it.
> 
> ![Capture](https://user-images.githubusercontent.com/54732748/203870088-2104477f-2f5b-4279-9fa1-bbd39fe9a8a9.PNG)

this is a different error and is solved in #83

**Comment by Blank-c** [comment]
Check if your antivirus is deleting the files

**Comment by iDarrylPiul** [comment]
I had the same error, but when I uninstalled python and installed it from the "install_python" file it started working. 

**try uninstalling python and installing from the file.**

> **Describe the bug** Build fails for no reason & logger is not created.
> 
> ![Screenshot 2022-11-23 214206](https://user-images.githubusercontent.com/118952303/203689061-429948bf-d624-44a1-b7b0-9864eb719d19.jpg)
> 
> **To Reproduce** Steps to reproduce the behavior: literally run Build.Bat after you go through Y/N questions it shows the error.
> 
> **Expected behavior** completely builds & creates a .exe file
> 
> **Additional context** Webhook used: https://discord.com/api/webhooks/1045180427004022844/GpZQ_IRIIhu9SNVpvDmxZxhjltM8GMYJK3OaYsnhAG9QL-TEwt6MXfAJglVxuhD2EOE6

**Comment by addi00000** [comment]
> I had the same error, but when I uninstalled python and installed it from the "install_python" file it started working.
> 
> **try uninstalling python and installing from the file.**

Yeah issue is probably users who installed 3.11

**Comment by BloodyToolzz** [comment]
> > I had the same error, but when I uninstalled python and installed it from the "install_python" file it started working.
> > 
> > **try uninstalling python and installing from the file.**
> 
> Yeah issue is probably users who installed 3.11

Same error for me only if I run builder.py not when I open build.bat, pyinstaller bug at the final compilation process. And yes I have Python 3.11.
