### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JustSparkyyy** [addi00000/empyrean#86]
**Describe the bug**
When you run main.exe after compiling give you errors sends you vault but not discord info

**To Reproduce**
run main.exe

**Screenshots**
![image](https://user-images.githubusercontent.com/112674500/203869918-8dd90318-418a-4f76-8f10-963d39ecd5c6.png)

**Comment by addi00000** [comment]
Should be fixed now. Please download latest release and rebuild
