### ISSUE TITLE
add all source codes to one py file

### ISSUE THREAD

**Issue by chiron853** [addi00000/empyrean#87]
can you make all source code scripts inside a py file and then add the option inside the py file like 'antidebug' = true because it asks these options everytime when i build and i cant use custom obfuscation too because of that

**Comment by chiron853** [comment]
@addi00000

**Comment by Blank-c** [comment]
try <kbd>[stickytape](https://pypi.org/project/stickytape/)</kbd>

**Comment by Blank-c** [comment]
check its documentation

**Comment by PandoricGalaxy** [comment]
> check its documentation

I did do but I'm not getting what to enter into the console

**Comment by addi00000** [comment]
Assuming that package works you just have to combine all the files in src/ dir

**Comment by chiron853** [comment]
time to try

**Comment by PandoricGalaxy** [comment]
> Assuming that package works you just have to combine all the files in src/ dir

Yeah ik I have to combine those files but what is the  command I need to put cause I can't understand the usage of the package

**Comment by addi00000** [comment]
So read the documentation?

**Comment by PandoricGalaxy** [comment]
> So read the documentation?

alright my bad it was pretty easy its just that i didnt understand what it meant.
Though for it to be of any use, i need to manually enter the configuration of the files. How do i manually enter the webhook? Like do i just paste the link instead of the _None_ or i put " " too then put in the webhook?
The other configs i think i just have to make true from false.

**Comment by addi00000** [comment]
Yes, the None in the webhook config need to be changed to a string using quotation marks

**Comment by PandoricGalaxy** [comment]
> Yes, the None in the webhook config need to be changed to a string using quotation marks

oh thanks, lol i was sitting in front of the screen for 45 mins waiting for you to reply xD

**Comment by addi00000** [comment]
I was taking a test from now to 45 mins ago 💀

**Comment by addi00000** [comment]
Can you confirm that the issue has been solved and that you made it onefile successfully?

**Comment by PandoricGalaxy** [comment]
Yes i do confirm, I just had to import stickytape and run this command:
`stickytape main.py > onefile.py`
where _onefile.py_ is any name i want and the command is ran in the src directory

**Comment by addi00000** [comment]
Cool

**Comment by PandoricGalaxy** [comment]
also does the injection automatically come to my webhook? cause i saw some your link to an encrypted injection too so idk i have to change it
