### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IshuPotatoe** [addi00000/empyrean#90]
**Describe the bug**
The bug occurs around the end of the build file. Everything goes blank and then this error pops up. Im not sure what the invalid input means or what is suppose to go there. Please anyone help.

**To Reproduce**
1. Go to 'builder.bat'
2. Click on 'builder.bat'
3. Wait for it to load
5. See error

**Expected behavior**
I expected the file to finish and create the file called build.exe

**Screenshots**
![image](https://user-images.githubusercontent.com/119264602/204162373-e6e7a2c5-ee80-49d6-9d09-89b4340fbcbf.png)
**Additional context**
The part blurred is my webhook (Not showing it to public).

**Comment by IshuPotatoe** [comment]
@addi00000

**Comment by YTxdXot1c** [comment]
i have the same issue

**Comment by YTxdXot1c** [comment]
@addi00000

**Comment by otkusay** [comment]
I have the same mistake

**Comment by addi00000** [comment]
You need to right click to paste in cmd. if that doesn't work you may have to right click the top bar and find the paste button
