### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pr1stak** [addi00000/empyrean#93]
**Describe the bug**
The thing cant send wifi data and system info

**To Reproduce**
Run the program

**Expected behavior**
To see information like on https://github.com/addi00000/empyrean/blob/main/img/em2.png

**Screenshots**
![image](https://user-images.githubusercontent.com/111359134/205151821-d0912c0c-8f3f-4397-9334-fb94c01ed0e1.png)

the last line is "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte"

**Comment by Co18** [comment]
goofy ahh error lmao
what os do you use ????

**Comment by Sazuko123** [comment]
i have it too

**Comment by Wizz1337** [comment]
same error | #99

**Comment by Your-Bestie-Was-Banned** [comment]
just add some catch blocks int he tokens.py file
