### ISSUE TITLE
[BUG] Pyinstaller issue when compiling

### ISSUE THREAD

**Issue by BloodyToolzz** [addi00000/empyrean#95]
Pyinstaller issue when it's compiling, antivirus is off btw.

**Screenshots**
![image](https://user-images.githubusercontent.com/106907415/205587678-a9d250ff-79b2-4a0c-a469-94c7facbe231.png)

**Additional context**
I just got Python 3.11, and empyrean was the first thing I ran

**Comment by addi00000** [comment]
uninstall python 3.11 and downgrade to python 3.10.x

**Comment by BloodyToolzz** [comment]
3.11 issue, needed to delete 3.11 and launch "install_python" file
