### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sazuko123** [addi00000/empyrean#98]
**Describe the bug**
inejection not work for me 

**To Reproduce**
1. Go to 'py.bat
2. Click on 'build.bat
3. Scroll down to 'do your webhooks and do y y y y y '

**Screenshots**
![Screenshot_20221206_125447](https://user-images.githubusercontent.com/119889544/205910346-a8c9a9c3-1323-4135-aff8-b05a69206bb5.png)

**Comment by Wizz1337** [comment]
there was non utf-8 character in your wifi data @addi00000 try to convert the value or just pass
